name: TIL Design System Pipeline
on: [push]
jobs:
  CI-CD-TIL-Design:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build-storybook
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './github-pages/'
      - uses: actions/deploy-pages@v4.0.5
